### ISSUE TITLE
Very Cool !!!

### ISSUE THREAD

**Issue by menduo** [ProgramFan/gitit-templates-enhanced#1]
Very cool. 

Learnt a lot from your projects, both https://github.com/ProgramFan/docker-gitit and https://github.com/ProgramFan/gitit-templates-enhanced 

I've forked docker-gitit and I will refactor gititi-bigger, then I will give you another big thanks in the README.

Thank you.

**Comment by ProgramFan** [comment]
Glad to see this tiny project helps you. :smile:
